/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;


public class App {
    public static void main(String[] args) {
      // penambahan anggota manual
      linkedlist ll = new linkedlist();
      linkedlist s = new linkedlist();
      ll.add(45);
      ll.add(20);
      ll.add(12);
      System.out.println(ll.print());

//      ll.checkval(45);

      
    }
}
